### ISSUE TITLE
ProjectId type representation

### ISSUE THREAD

**Issue by KristianJakubik** [Kentico/content-management-sdk-net#30]
### Expected result

Hi,
I would need to clarify, what is the proper way to represent the type of `ProjectId`. 
In issue #3, I am implementing response object, which contains property `ProjectId` and  to the best of my knowledge this property should be type of `Guid` (other Ids are represented this way).
However in source code it is type of  `string`.

### Resources

https://github.com/Kentico/content-management-sdk-net/blob/ded1797c4be6aadb0f98a5de439528173c8f4e45/KenticoCloud.ContentManagement/Configuration/ContentManagementOptions.cs#L15-L18
https://github.com/Kentico/content-management-sdk-net/blob/ded1797c4be6aadb0f98a5de439528173c8f4e45/KenticoCloud.ContentManagement.Tests/ContentManagementClientTests.cs#L23

**Comment by petrsvihlik** [comment]
Hey @KristianJakubik, it'll always be `Guid`. See this for instance:

https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/DeliveryClient.cs#L113

I think the reason why it's string at some places is that it's more convenient for users to enter just `"49f108e5-2e7e-4405-8369-7e0cf92576f2"` instead of creating `new Guid("49f108e5-2e7e-4405-8369-7e0cf92576f2")` while passing it as an argument.
